### PR TITLE
fix: Allow for geo data to contain null Lat or Long (temporary)

### LINKED ISSUE #379: [Bug]: Geo data coming through without Long / Lat
## Description
Site build failing because Long & Lat are required attributes. Some of the PlaceCal data appears to be missing them.

```

-- Static Http Decoding Error --------------- TODO - path from request
--
12:23:32.692 | I encountered some errors while decoding this JSON:
12:23:32.692 |  
12:23:32.692 | At path /data/eventsByFilter/275
12:23:32.692 |  
12:23:32.692 | Json.Decode.oneOf failed in the following 2 ways:
12:23:32.692 |  
12:23:32.693 |  
12:23:32.693 |  
12:23:32.693 | (1) Problem with the value at json.longitude:
12:23:32.693 |  
12:23:32.693 | null
12:23:32.693 |  
12:23:32.694 | Expecting a STRING
12:23:32.694 |  	-- Static Http Decoding Error --------------- TODO - path from request
12:23:32.692	I encountered some errors while decoding this JSON:
12:23:32.692	
12:23:32.692	At path /data/eventsByFilter/275
12:23:32.692	
12:23:32.692	  Json.Decode.oneOf failed in the following 2 ways:
12:23:32.692	
12:23:32.693	
12:23:32.693	
12:23:32.693	(1) Problem with the value at json.longitude:
12:23:32.693	    
12:23:32.693	        null
12:23:32.693	    
12:23:32.694	    Expecting a STRING
12:23:32.694	
12:23:32.694	
12:23:32.694	
12:23:32.694	(2) Problem with the given value:
12:23:32.694	    
12:23:32.694	    {
12:23:32.694	            "latitude": null,
12:23:32.695	            "longitude": null
12:23:32.695	        }
12:23:32.695	    
12:23:32.695	    Expecting null
12:23:32.695	
12:23:32.695	    {
12:23:32.695	      "id": "323631",
12:23:32.695	      "name": "LxZ NYE - the black and gold party",
12:23:32.695	      "summary": "LxZ NYE - the black and gold party",
12:23:32.696	      "description": "Seeking a lesbian NYE party in London where you can shake your booty\nsurrounded by queer love in the heart of Central London? Looking to\nmingle with London's finest bisexual, non binary, trans and GNC babes as\nyou see in another year?Get your fine queer ass decked out in black or\ngold (or both. ) and come celebrate the end of another eventful year\nwith the LxZ events family at one of the city's most exciting bar and\nclubs - Core.Set over two floors, this sexy 400 capacity venue will be a\nqueer hotspot of your favourite dance, hiphop, trap, house, R&amp;amp;B\nand UK Garage tracks as we welcome 2023 with a bang.As always, the best\ndressed will win a boozy prize - so get shopping/sorting through your\nparty wardrobe. Our theme this year is blingtastic black and gold.You\ndon't want to miss London's sexiest night of queer glamour, joy and\ncelebration - get those early bird tickets fast before it's too late.\nDJs SizzlesShaynLDN YazMystery DJ This is due to be a sell out event, so\ntell your people and get your tickets before they go and the FOMO\nmonster gets you - he's not pretty… *Dress code: Black and/or Gold -\nbejewelled party dresses, obscenely flashy suits, gold tracksuits - you\ndecide. Just make it gay. \\*Lone Rangers needing party buddies contact\nus to hook you up*Gay boy buddies and trans men always welcome *Tables\navailable for anyone wanting to BALLER it up -\nsparklers/bottles/birthdays etc - contact us for bottle prices \\*No\ntoxic masculinity - we have the right to refuse entry*good vibes only\n\\*No government photographic ID no entry \\*LAST ENTRY 1AM NO REFUNDS -\nunless the event is cancelled",
12:23:32.696	      "startDate": "2022-12-31T22:00:00+00:00",
12:23:32.696	      "endDate": "2023-01-01T03:00:00+00:00",
12:23:32.696	      "publisherUrl": null,
12:23:32.696	      "address": {
12:23:32.696	        "streetAddress": "Core Bar, 10-15 Queen Street, London",
12:23:32.696	        "postalCode": "EC4N 1TY",
12:23:32.696	        "geo": {
12:23:32.697	          "latitude": null,
12:23:32.697	          "longitude": null
12:23:32.697	        }
12:23:32.697	      },
12:23:32.697	      "organizer": {
12:23:32.697	        "id": "190"
12:23:32.697	      }
12:23:32.697	    }
12:23:32.698	1 /all-paths.json: 12.460s
12:23:32.694 |  
12:23:32.694 |  
12:23:32.694 | (2) Problem with the given value:
12:23:32.694 |  
12:23:32.694 | {
12:23:32.694 | "latitude": null,
12:23:32.695 | "longitude": null
12:23:32.695 | }
12:23:32.695 |  
12:23:32.695 | Expecting null
12:23:32.695 |  
12:23:32.695 | {
12:23:32.695 | "id": "323631",
12:23:32.695 | "name": "LxZ NYE - the black and gold party",
12:23:32.695 | "summary": "LxZ NYE - the black and gold party",
12:23:32.696 | "description": "Seeking a lesbian NYE party in London where you can shake your booty\nsurrounded by queer love in the heart of Central London? Looking to\nmingle with London's finest bisexual, non binary, trans and GNC babes as\nyou see in another year?Get your fine queer ass decked out in black or\ngold (or both. ) and come celebrate the end of another eventful year\nwith the LxZ events family at one of the city's most exciting bar and\nclubs - Core.Set over two floors, this sexy 400 capacity venue will be a\nqueer hotspot of your favourite dance, hiphop, trap, house, R&amp;amp;B\nand UK Garage tracks as we welcome 2023 with a bang.As always, the best\ndressed will win a boozy prize - so get shopping/sorting through your\nparty wardrobe. Our theme this year is blingtastic black and gold.You\ndon't want to miss London's sexiest night of queer glamour, joy and\ncelebration - get those early bird tickets fast before it's too late.\nDJs SizzlesShaynLDN YazMystery DJ This is due to be a sell out event, so\ntell your people and get your tickets before they go and the FOMO\nmonster gets you - he's not pretty… *Dress code: Black and/or Gold -\nbejewelled party dresses, obscenely flashy suits, gold tracksuits - you\ndecide. Just make it gay. \\*Lone Rangers needing party buddies contact\nus to hook you up*Gay boy buddies and trans men always welcome *Tables\navailable for anyone wanting to BALLER it up -\nsparklers/bottles/birthdays etc - contact us for bottle prices \\*No\ntoxic masculinity - we have the right to refuse entry*good vibes only\n\\*No government photographic ID no entry \\*LAST ENTRY 1AM NO REFUNDS -\nunless the event is cancelled",
12:23:32.696 | "startDate": "2022-12-31T22:00:00+00:00",
12:23:32.696 | "endDate": "2023-01-01T03:00:00+00:00",
12:23:32.696 | "publisherUrl": null,
12:23:32.696 | "address": {
12:23:32.696 | "streetAddress": "Core Bar, 10-15 Queen Street, London",
12:23:32.696 | "postalCode": "EC4N 1TY",
12:23:32.696 | "geo": {
12:23:32.697 | "latitude": null,
12:23:32.697 | "longitude": null
12:23:32.697 | }
12:23:32.697 | },
12:23:32.697 | "organizer": {
12:23:32.697 | "id": "190"
12:23:32.697 | }
12:23:32.697 | }
12:23:32.698 | 1 /all-paths.json: 12.460s

```

### PR DESCRIPTION
**Pull request by katjam**
Fixes #379 

## Description

- Temporarily allow address values from PlaceCal to have missing lat and long
- Default to 0, 0 and do not render in maps

### CODE REVIEW

File: src/Data/PlaceCal/Events.elm [hunk 1]
```diff
@@ -46,8 +46,11 @@ type alias EventLocation =
 
 
 type alias Geo =
-    { latitude : String
-    , longitude : String
+    -- Bug: We expect if there is a postcode in the address, these exist.
+    -- But, in practice, sometimes they don't see:
+    -- https://github.com/geeksforsocialchange/PlaceCal/issues/1639
+    { latitude : Maybe String
```
Comment (katjam) [inline src/Data/PlaceCal/Events.elm:52]: Note I am not changing these property keys to `maybeLatitude` and `maybeLongitude` because I expect this bug to be temporary and that seemed to obscure for me.

**Review by ivan-kocienski-gfsc — APPROVED** [review]
I have replicated the bad data on my local machine and rebuilt TD which had no problems.

Looks okay to me

File: src/Data/PlaceCal/Events.elm (hunk 1 above)
Comment (ivan-kocienski-gfsc) [reply src/Data/PlaceCal/Events.elm:52]: i think the problem is on PC side: it really should return null on the geo field if the data is missing. how likely is there to be a latitude without a longitude?

Comment (katjam) [reply src/Data/PlaceCal/Events.elm:52]: It is an error in PlaceCal - but Kim and I decided there is no harm guarding against it here.
https://github.com/geeksforsocialchange/PlaceCal/issues/1639

It is unlikely to have lat without long or vice-versa but nothing is impossible as we know so it feels less arbitrary to do it definitively this way.
