### PR TITLE
WIP: Use timezone for date/time conversion

### LINKED ISSUE #448: [Bug]: UTC time is not correct for UK during BST
## Description
Events in The Trans Dimension calculate their time by converting ISO8601 string to UTC this is incorrect for some of the year

image

See https://www.gov.uk/when-do-the-clocks-change for ref on how to figure out whether we are in summertime

### PR DESCRIPTION
**Pull request by james-collapse**
Fixes #448 

## Description

- It was observed that event times were incorrect during BST (GMT + 01:00).

## Why was this happening?

- Event times in GraphQL are in ISO 8601 format - for example: `"2025-05-26T20:00:00+01:00"`.
- We use `Iso8601.toTime` to convert ISO 8601 date strings into Posix times.
- `Iso8601.toTime` normalises ISO 8601 date strings with an offset - in this case, converting `20:00:00` to `19:00:00`.
- We then used `DateFormat.format` to convert the Posix time into a human-readable string.
- `DateFormat.format` expects a timezone - we were using `utc` rather than the actual timezone, which meant that we were presenting the normalised UTC time.

Now, the app gets the user's timezone and passes it into `DateFormat.format`, so the correct time is presented.

Before:

Screenshot 2025-05-26 at 16 48 52
Screenshot 2025-05-26 at 16 50 21

After:

Screenshot 2025-05-26 at 16 49 12
Screenshot 2025-05-26 at 16 50 56

Note: This is a WIP because I've only applied the change to time, not to days/months/years as well.

### CODE REVIEW

File: app/Route/Events/Event_.elm [hunk 1]
```diff
@@ -89,7 +90,7 @@ eventMetaTagTitle event =
             TransDate.humanDayDateMonthFromPosix event.startDatetime
 
         ( eventHourStart, eventHourEnd ) =
-            ( TransDate.humanTimeFromPosix event.startDatetime, TransDate.humanTimeFromPosix event.endDatetime )
+            ( TransDate.humanTimeFromPosix event.startDatetime utc, TransDate.humanTimeFromPosix event.endDatetime utc )
```
Comment (james-collapse) [inline app/Route/Events/Event_.elm:93]: How important is it that we have the local time in the event meta tags? I could add it, it's just a bit of extra work to include here.

Comment (katjam) [reply app/Route/Events/Event_.elm:93]: I think spin off a new issue so we can get this massive improvement in without further faff.

**Review by katjam — APPROVED** [review]
This looks perfect! Thank you for getting rid of the hardcoded timezone.
